# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.21.0+dev-543-gced34bab1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.change_files_options import ChangeFilesOptions  # noqa: E501
from swagger_client.rest import ApiException


class TestChangeFilesOptions(unittest.TestCase):
    """ChangeFilesOptions unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangeFilesOptions(self):
        """Test ChangeFilesOptions"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.change_files_options.ChangeFilesOptions()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
