# coding: utf-8

"""
    Gitea API.

    This documentation describes the Gitea API.  # noqa: E501

    OpenAPI spec version: 1.21.0+dev-543-gced34bab1
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.change_file_operation import ChangeFileOperation  # noqa: E501
from swagger_client.rest import ApiException


class TestChangeFileOperation(unittest.TestCase):
    """ChangeFileOperation unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testChangeFileOperation(self):
        """Test ChangeFileOperation"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.change_file_operation.ChangeFileOperation()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
